# Generated by Django 4.1.3 on 2022-11-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=150)),
                ('f_nacimiento', models.DateField()),
                ('f_exp_documento', models.DateField()),
                ('documento', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('l_exp_documento', models.CharField(max_length=30)),
                ('ciud_residencia', models.CharField(max_length=30)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('n_pedido', models.DateField(primary_key=True, serialize=False)),
                ('productos', models.CharField(max_length=500)),
                ('valor_producto', models.FloatField()),
                ('producto_mas_transporte', models.FloatField()),
                ('tamaño_producto', models.CharField(max_length=15)),
                ('incremento', models.FloatField()),
                ('proveedor', models.CharField(max_length=100)),
                ('cantidad_productos', models.IntegerField()),
                ('tiempo_entrega', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.cliente')),
            ],
        ),
    ]
