# Generated by Django 4.1.3 on 2022-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_alter_cliente_apellido_alter_cliente_ciud_residencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tiempo_entrega',
            field=models.CharField(max_length=10),
        ),
    ]
