# Generated by Django 4.1.3 on 2022-11-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_alter_pedido_tiempo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(max_length=10),
        ),
    ]
