# Generated by Django 4.1.3 on 2022-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0011_alter_cliente_celular_alter_cliente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
