# Generated by Django 4.1.3 on 2022-11-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0012_alter_cliente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
